Added towers (not attacking yet, do disappear on hitting 0 health)
ptal/lol2D pull request #33
Opened 2021-05-11 13:59 UTC by GwenTinho

2021-05-11 17:55 UTC, ptal commented on src/main/java/lol/server/CodeRunner.java
> +public class CodeRunner {
Ubuntu + Sublime Text + Terminal FTW.

2021-05-11 20:07 UTC, ptal requested changes

2021-05-11 20:20 UTC, AlexanderG97 commented on src/main/java/lol/game/Team.java
> +      turn.registerAction(new TowerSpawn(teamID, 3, 6));
To be honest I thought I might need to change this behavior in order to change the destroy behavior. Turned out not to be the case and this is equivalent.
I would say it's less hard-coded than before as now the position variables could be changed and could be set to some variable that changes with the size of the board.

2021-05-11 20:33 UTC, ptal commented on src/main/java/lol/game/Team.java
> +        if(d.currentHP <= 0) {
it should stay protected I think. But the class `Team` cannot access protected member of a class it does not inherit from.

2021-05-12 06:01 UTC, ptal commented on src/main/java/lol/game/Team.java
> +        if(d.currentHP <= 0) {
No, protected attributes are only accessible by the classes inheriting from the parent class. Where did you see that package access thing?

2021-05-12 06:51 UTC, AlexanderG97 commented on src/main/java/lol/game/Team.java
> +        if(d.currentHP <= 0) {
https://www.w3schools.com/java/ref_keyword_protected.asp#:~:text=The%20protected%20keyword%20is%20an,the%20same%20package%20and%20subclasses.
Should I change them back to protected?

2021-05-12 07:42 UTC, ptal commented on src/main/java/lol/game/Team.java
> +        if(d.currentHP <= 0) {
Ok, I didn't know that, you just fixed a hole in my Java understanding, this rule doesn't apply to C++, I must have confused the two!
Normally, we don't access protected members across a package, as it weakens encapsulation.

You can keep it private, perhaps we won't need it protected after all.

2021-05-12 08:10 UTC, AlexanderG97 commented on src/main/java/lol/game/Team.java
> +        if(d.currentHP <= 0) {
OK, I guess it's ready to merge now?

2021-05-12 08:23 UTC, ptal requested changes
We are almost there! Some very easy fix to be made and I merge.

2021-05-12 08:23 UTC, ptal commented on src/main/java/lol/client/ai/RandomAITower.java
> +public class RandomAITower extends AIBase {
This class shares almost all its code with `RandomAI`. Please inherits from RandomAI, extract some methods (to attack nexus, and move) as protected methods, and use that in your `RandomAITower` to make it much smaller.

2021-05-12 08:23 UTC, ptal commented on src/main/java/lol/game/Battlefield.java
> +import javax.swing.text.html.Option;
no need for this import?

2021-05-12 08:23 UTC, ptal commented on src/main/java/lol/game/Tower.java
> +    public static final int BLUE = 0;
use Nexus.BLUE and Nexus.RED, this is to avoid mixing up the constant.

2021-05-12 09:12 UTC, merged